import { Metropolis, poppins } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${poppins.variable} ${Metropolis.variable} font-poppins`}
      >
        {children}
      </body>
    </html>
  );
}
